### ISSUE TITLE
Fatal Error After Install

### ISSUE THREAD

**Issue by jgmac1106** [mapkyca/known-ipfs#6]
I am getting a 500 error after installing the plugin:

 > Oh no! Known experienced a problem!
> 
> Known experienced a problem with this page and couldn't continue.
> 
> Uncaught Error: Call to undefined method Idno\Core\Idno::routes() in /home/jgregory/public_html/quickthoughts/IdnoPlugins/IPFS/Main.php:11
> 
> The technical details are as follows:
> 
> Fatal Error: /home/jgregory/public_html/quickthoughts/IdnoPlugins/IPFS/Main.php:11 - "Uncaught Error: Call to undefined method Idno\Core\Idno::routes() in /home/jgregory/public_html/quickthoughts/IdnoPlugins/IPFS/Main.php:11
> Stack trace:
> #0 /home/jgregory/public_html/quickthoughts/Idno/Common/Component.php(19): IdnoPlugins\IPFS\Main->registerPages()
> #1 /home/jgregory/public_html/quickthoughts/Idno/Core/Plugins.php(66): Idno\Common\Component->__construct()
> #2 /home/jgregory/public_html/quickthoughts/Idno/Common/Component.php(17): Idno\Core\Plugins->init()
> #3 /home/jgregory/public_html/quickthoughts/Idno/Core/Idno.php(252): Idno\Common\Component->__construct()
> #4 /home/jgregory/public_html/quickthoughts/Idno/Common/Component.php(19): Idno\Core\Idno->registerPages()
> #5 /home/jgregory/public_html/quickthoughts/Idno/Core/Idno.php(44): Idno\Common\Component->__construct()
> #6 /home/jgregory/public_html/quickthoughts/Idno/start.php(149): Idno\Core\Idno->__construct()
> #7 /home/jgregory/public_html/quickthoughts/index.php(25): require_once('/home/jgregory/...')
> #8 {main}
>   thrown", on page quickthoughts.jgregorymcverry.com/admin/plugins/
>

**Comment by mapkyca** [comment]
Update to the latest Known - lots of class changes. :)

**Comment by jgmac1106** [comment]
Do we use the packages page on your website or GitHub?

**Comment by mapkyca** [comment]
Github. Or at least, GitHub until I get home tonight and have a chance to rebuild the packages :)
